=== ermus19/cgi-kenken/xml/kenkenSchema.xsd
<?xml version="1.1" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://agora.unileon.es"
xmlns="http://agora.unileon.es"
elementFormDefault="qualified">

  <!-- Grupo de atributos para definir los límites en una casilla que enmarcan un poliminó en un solitario Kenken. Los bordes exteriores de un solitario kenken siempre forman parte de los límites de un poliminó -->
  <xs:attributeGroup name="limitesPolimino">
    <xs:attribute name="norte" type="xs:boolean"/>
    <xs:attribute name="sur" type="xs:boolean"/>
    <xs:attribute name="este" type="xs:boolean"/>
    <xs:attribute name="oeste" type="xs:boolean"/>
  </xs:attributeGroup>

  <!-- Tipo auxiliar para combinar una restricción y atributos -->
  <xs:simpleType name="expresionKenken">
     <xs:restriction base="xs:token">
      <xs:pattern value="[0-9]*[-+x÷]?"/>
     </xs:restriction>
  </xs:simpleType>
  
  <!-- Una casilla kenken puede contener una operación definida por un número positivo seguido de una operación, un valor solución  o puede estar vacía.
       El atributo 'numero' de la casilla indica su posición dentro de la fila (comenzando en 1).
  Los atributos del grupo 'limitesPolimino' definen si la casilla define algún límite para un poliminó. -->
  <xs:complexType name="casillaKenken">
      <xs:all>
         <xs:element name="operacion" type="expresionKenken" minOccurs="0"/>
         <xs:element name="solucion" type="xs:positiveInteger" minOccurs="0"/>
      </xs:all>
      <xs:attribute name="numero" type="xs:positiveInteger" use="required"/>
      <xs:attributeGroup ref="limitesPolimino"/>
   </xs:complexType>

   <!-- Una fila kenken define las casillas con su contenido (todo optativo): número más operación y valor solución. Los atributos de casilla definen los límites de  los poliminós.
	El atributo 'numero' de la fila indica su posición dentro del solitario kenken (comenzando en 1). -->
   <xs:complexType name="filaKenken">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="casilla" type="casillaKenken"/>
    </xs:sequence>
    <xs:attribute name="numero" type="xs:positiveInteger" use="required"/>
   </xs:complexType>

   <!-- Un kenken viene definido por su tamaño, atributos 'filas' y 'columnas', y por las filas que contiene. Si una casilla no tiene contenido o no tiene ningún límite de un poliminó puede no aparecer en su fila. Si una fila no tiene ninguna casilla con contenido tampoco aparecerá en la definición del kenken. -->
  <xs:element name="kenken">
    <xs:complexType>
      <xs:sequence>
	<xs:element name="fila" type="filaKenken" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="filas" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ermus19/cgi-kenken/xml/kenken1_sol.xml
<?xml version="1.1" encoding="UTF-8" ?>

<kenken filas="6"
xmlns="http://agora.unileon.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://agora.unileon.es kenkenSchema.xsd">

  <fila numero="1">
    <casilla numero="1" norte="true" este="true" sur="false" oeste="true">
      <operacion>11+</operacion>
      <solucion>5</solucion>
    </casilla>
    <casilla numero="2" norte="true" este="false" sur="true" oeste="true">
      <operacion>2รท</operacion>
      <solucion>6</solucion>
    </casilla>
    <casilla numero="3" norte="true" este="true" sur="true" oeste="false">
            <solucion>3</solucion>
    </casilla>
    <casilla numero="4" norte="true" este="true" sur="false" oeste="true">
      <operacion>20x</operacion>
      <solucion>4</solucion>
    </casilla>
    <casilla numero="5" norte="true" este="false" sur="true" oeste="true">
      <operacion>6x</operacion>
      <solucion>1</solucion>
    </casilla>
    <casilla numero="6" norte="true" este="true" sur="false" oeste="false">
            <solucion>2</solucion>
    </casilla>
  </fila>

  <fila numero="2">
    <casilla numero="1" norte="false" este="true" sur="true" oeste="true">
            <solucion>6</solucion>
    </casilla>
    <casilla numero="2" norte="true" este="false" sur="true" oeste="true">
      <operacion>3-</operacion>
      <solucion>1</solucion>
    </casilla>
    <casilla numero="3" norte="true" este="true" sur="true" oeste="false">
            <solucion>4</solucion>
    </casilla>
    <casilla numero="4" norte="false" este="true" sur="true" oeste="true">
            <solucion>5</solucion>
    </casilla>
    <casilla numero="5" norte="true" este="true" sur="false" oeste="true">
      <operacion>3รท</operacion>
      <solucion>2</solucion>
    </casilla>
    <casilla numero="6" norte="false" este="true" sur="false" oeste="true">
            <solucion>3</solucion>
    </casilla>
  </fila>

    <fila numero="3">
    <casilla numero="1" norte="true" este="false" sur="false" oeste="true">
      <operacion>240x</operacion>
      <solucion>4</solucion>
    </casilla>
    <casilla numero="2" norte="true" este="true" sur="false" oeste="false">
            <solucion>5</solucion>
    </casilla>
    <casilla numero="3" norte="true" este="false" sur="true" oeste="true">
      <operacion>6x</operacion>
      <solucion>2</solucion>
    </casilla>
    <casilla numero="4" norte="true" este="true" sur="true" oeste="false">
            <solucion>3</solucion>
    </casilla>
    <casilla numero="5" norte="false" este="true" sur="true" oeste="true">
            <solucion>6</solucion>
    </casilla>
    <casilla numero="6" norte="false" este="true" sur="true" oeste="true">
                  <solucion>1</solucion>
    </casilla>
  </fila>

  <fila numero="4">
    <casilla numero="1" norte="false" este="false" sur="true" oeste="true">
            <solucion>3</solucion>
    </casilla>
    <casilla numero="2" norte="false" este="true" sur="true" oeste="false">
            <solucion>4</solucion>
    </casilla>
    <casilla numero="3" norte="true" este="true" sur="false" oeste="true">
      <operacion>6x</operacion>
      <solucion>1</solucion>
    </casilla>
    <casilla numero="4" norte="true" este="true" sur="false" oeste="true">
      <operacion>7+</operacion>
            <solucion>2</solucion>
    </casilla>
    <casilla numero="5" norte="true" este="false" sur="true" oeste="true">
      <operacion>30x</operacion>
      <solucion>5</solucion>
    </casilla>
    <casilla numero="6" norte="true" este="true" sur="true" oeste="false">
            <solucion>6</solucion>
    </casilla>
  </fila>

   <fila numero="5">
    <casilla numero="1" norte="true" este="false" sur="true" oeste="true">
      <operacion>6x</operacion>
      <solucion>2</solucion>
    </casilla>
    <casilla numero="2" norte="true" este="true" sur="true" oeste="false">
            <solucion>3</solucion>
    </casilla>
    <casilla numero="3" norte="false" este="true" sur="true" oeste="true">
            <solucion>6</solucion>
    </casilla>
    <casilla numero="4" norte="false" este="false" sur="true" oeste="true">
            <solucion>1</solucion>
    </casilla>
    <casilla numero="5" norte="true" este="true" sur="true" oeste="false">
            <solucion>4</solucion>
    </casilla>
    <casilla numero="6" norte="true" este="true" sur="false" oeste="true">
      <operacion>9+</operacion>
                  <solucion>5</solucion>
    </casilla>
</fila>

<fila numero="6">
    <casilla numero="1" norte="true" este="false" sur="true" oeste="true">
      <operacion>8+</operacion>
                  <solucion>1</solucion>
    </casilla>
    <casilla numero="2" norte="true" este="false" sur="true" oeste="false">
            <solucion>2</solucion>
    </casilla>
    <casilla numero="3" norte="true" este="true" sur="true" oeste="false">
            <solucion>5</solucion>
    </casilla>
    <casilla numero="4" norte="true" este="false" sur="true" oeste="true">
      <operacion>2รท</operacion>
      <solucion>6</solucion>
    </casilla>
    <casilla numero="5" norte="true" este="true" sur="true" oeste="false">
            <solucion>3</solucion>
    </casilla>
    <casilla numero="6" norte="false" este="true" sur="true" oeste="true">
            <solucion>4</solucion>
    </casilla>
</fila>

</kenken>
